### ISSUE TITLE
HTTP 201 when creating new task

### ISSUE THREAD

**Issue by torusfw** [dgreen99/org.eclipse.mylyn.github#18]
From today, creating new tasks fails with an HTTP 201 "error".
Maybe an API/behaviour change at github, since when you refresh the query, the issue is in fact created on the server side (and then I have to delete the initial task, since it is duplicated...)

**Comment by NobleUplift** [comment]
There's an official Mylyn connector for GitHub?! Someone should provide a link or make it more obvious that this repository is deprecated.

**Comment by dgreen99** [comment]
Apologies for the confusion.  I will make it more obvious.
